# Generated by Django 4.2.6 on 2023-12-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pic',
            field=models.CharField(max_length=300),
        ),
    ]
